# Generated by Django 5.2.4 on 2026-06-25 17:52

import api.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('lang_name', models.CharField(max_length=25, unique=True)),
                ('yt_dlp_lang', models.CharField(default='', max_length=25)),
                ('tesseract_langcode', models.CharField(default='', max_length=25)),
            ],
            options={
                'db_table': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('channel_img', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_name', models.CharField(max_length=30)),
                ('channel_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('channel_private', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(db_column='is_favorite', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL)),
                ('native_language', models.ForeignKey(db_column='nat_id', on_delete=django.db.models.deletion.CASCADE, related_name='channel_native', to='api.language')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('editor_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Editors',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('doc_file', models.FileField(blank=True, null=True, upload_to=api.models.lesson_file_upload_path)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=api.models.audio_file_upload_path)),
                ('audio_folder', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, default='images/default-01.jpg', null=True, upload_to=api.models.image_file_upload_path)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('lesson_private', models.BooleanField(default=False)),
                ('audioUploaded', models.BooleanField(default=False)),
                ('fileUploaded', models.BooleanField(default=False)),
                ('urlReference', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('native_language', models.ForeignKey(db_column='nat_id', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_native', to='api.language')),
                ('target_language', models.ForeignKey(db_column='tar_id', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_target', to='api.language')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Lesson',
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('phrase', models.CharField(max_length=60)),
                ('language', models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.CASCADE, to='api.language')),
            ],
            options={
                'db_table': 'Phrases',
            },
        ),
        migrations.CreateModel(
            name='PhraseTranslation',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('definition', models.TextField(blank=True, null=True)),
                ('native_language', models.ForeignKey(db_column='nat_id', on_delete=django.db.models.deletion.CASCADE, related_name='phrase_translations_native', to='api.language')),
                ('phrase', models.ForeignKey(db_column='phrase_id', on_delete=django.db.models.deletion.CASCADE, to='api.phrase')),
                ('target_language', models.ForeignKey(db_column='tar_id', on_delete=django.db.models.deletion.CASCADE, related_name='phrase_translations_target', to='api.language')),
                ('user', models.ForeignKey(db_column='user_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Phrase_Translations',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=50)),
                ('report_date', models.DateField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('audio_file', models.CharField(blank=True, max_length=50, null=True)),
                ('sentence', models.CharField(max_length=250)),
                ('start_ms', models.PositiveIntegerField(default=0)),
                ('end_ms', models.PositiveIntegerField(default=0)),
                ('translated_sentence', models.CharField(max_length=250)),
                ('lesson', models.ForeignKey(db_column='lesson_id', on_delete=django.db.models.deletion.CASCADE, to='api.lesson')),
                ('lesson_language', models.ForeignKey(db_column='lesson_lang_id', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_sentences', to='api.language')),
                ('translate_language', models.ForeignKey(db_column='translate_lang_id', on_delete=django.db.models.deletion.CASCADE, related_name='translation_sentences', to='api.language')),
            ],
            options={
                'db_table': 'Sentence',
            },
        ),
        migrations.CreateModel(
            name='UserLessonsProgress',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('current_lesson_index', models.SmallIntegerField(default=0)),
                ('last_viewed', models.DateField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(db_column='lesson_id', default=7, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_lessons_progress',
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('profile_img', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_docs', models.SmallIntegerField(default=0)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('logged_hours', models.IntegerField(default=0)),
                ('graph_type', models.CharField(blank=True, max_length=20, null=True)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('native_language', models.ForeignKey(db_column='native_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_native', to='api.language')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_lesson', models.ForeignKey(db_column='lesson_progress', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userlessonsprogress')),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('notifications', models.BooleanField(db_column='notifications', default=True)),
                ('dictionary_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_set_volume', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('user_set_speed', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('repeat_audio', models.BooleanField(db_column='repeat_audio', default=False)),
                ('repeat_audio_all', models.BooleanField(db_column='repeat_audio_all', default=False)),
                ('shuffle_audio', models.BooleanField(db_column='shuffle_audio', default=False)),
                ('native_language', models.ForeignKey(db_column='nat_id', on_delete=django.db.models.deletion.CASCADE, related_name='settings_translations_native', to='api.language')),
                ('target_language', models.ForeignKey(db_column='tar_id', on_delete=django.db.models.deletion.CASCADE, related_name='settings_translations_target', to='api.language')),
                ('user', models.ForeignKey(db_column='user_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=30)),
                ('frequency', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('language', models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.CASCADE, to='api.language')),
            ],
            options={
                'db_table': 'Words',
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('frequency', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('review_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(db_column='word_id', on_delete=django.db.models.deletion.CASCADE, to='api.word')),
            ],
            options={
                'db_table': 'User_Words',
            },
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('definition', models.TextField(blank=True, null=True)),
                ('native_language', models.ForeignKey(db_column='nat_id', on_delete=django.db.models.deletion.CASCADE, related_name='word_translations_native', to='api.language')),
                ('target_language', models.ForeignKey(db_column='tar_id', on_delete=django.db.models.deletion.CASCADE, related_name='word_translations_target', to='api.language')),
                ('user', models.ForeignKey(db_column='user_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(db_column='word_id', on_delete=django.db.models.deletion.CASCADE, to='api.word')),
            ],
            options={
                'db_table': 'Word_Translations',
            },
        ),
        migrations.CreateModel(
            name='ChannelVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('channel', 'user')},
            },
        ),
    ]
