# Generated by Django 5.2.4 on 2025-07-24 18:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('lang_name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('phrase', models.CharField(max_length=60)),
                ('language', models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.CASCADE, to='api.language')),
            ],
            options={
                'db_table': 'Phrases',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('native_language', models.ForeignKey(db_column='native_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_native', to='api.language')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=50)),
                ('report_date', models.DateField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('profile_img', models.CharField(blank=True, max_length=255, null=True)),
                ('streak', models.IntegerField(default=0)),
                ('uploaded_docs', models.SmallIntegerField(default=0)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('logged_hours', models.IntegerField(default=0)),
                ('graph_type', models.CharField(blank=True, max_length=20, null=True)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='PhraseTranslation',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('definition', models.TextField(blank=True, null=True)),
                ('native_language', models.ForeignKey(db_column='nat_id', on_delete=django.db.models.deletion.CASCADE, related_name='phrase_translations_native', to='api.language')),
                ('phrase', models.ForeignKey(db_column='phrase_id', on_delete=django.db.models.deletion.CASCADE, to='api.phrase')),
                ('target_language', models.ForeignKey(db_column='tar_id', on_delete=django.db.models.deletion.CASCADE, related_name='phrase_translations_target', to='api.language')),
                ('user', models.ForeignKey(db_column='user_ID', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Phrase_Translations',
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('editor_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Editors',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('doc_file', models.BinaryField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=30)),
                ('language', models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.CASCADE, to='api.language')),
            ],
            options={
                'db_table': 'Words',
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('frequency', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('word', models.ForeignKey(db_column='word_id', on_delete=django.db.models.deletion.CASCADE, to='api.word')),
            ],
            options={
                'db_table': 'User_Words',
            },
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('definition', models.TextField(blank=True, null=True)),
                ('native_language', models.ForeignKey(db_column='nat_id', on_delete=django.db.models.deletion.CASCADE, related_name='word_translations_native', to='api.language')),
                ('target_language', models.ForeignKey(db_column='tar_id', on_delete=django.db.models.deletion.CASCADE, related_name='word_translations_target', to='api.language')),
                ('user', models.ForeignKey(db_column='user_ID', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('word', models.ForeignKey(db_column='word_id', on_delete=django.db.models.deletion.CASCADE, to='api.word')),
            ],
            options={
                'db_table': 'Word_Translations',
            },
        ),
    ]
