# Generated by Django 5.2.4 on 2026-06-25 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_lesson',
            field=models.ForeignKey(blank=True, db_column='lesson_progress', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userlessonsprogress'),
        ),
    ]
