# Generated by Django 5.2.4 on 2026-07-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
