# Generated by Django 5.2.4 on 2026-03-13 14:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, default='images/default-01.jpg', null=True, upload_to=api.models.image_file_upload_path),
        ),
    ]
