# Generated by Django 5.2.4 on 2025-08-02 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_wordtranslation_user_alter_profile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('native_language', models.ForeignKey(db_column='nat_id', on_delete=django.db.models.deletion.CASCADE, related_name='settings_translations_native', to='api.language')),
                ('target_language', models.ForeignKey(db_column='tar_id', on_delete=django.db.models.deletion.CASCADE, related_name='settings_translations_target', to='api.language')),
                ('user', models.ForeignKey(db_column='user_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
