# Generated by Django 5.2.4 on 2026-08-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recording_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('m2m100', 'M2M100'), ('opus', 'OPUS')], max_length=50)),
                ('model_name', models.CharField(max_length=255)),
                ('save_path', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
