# Generated by Django 5.2.4 on 2026-06-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_current_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='audio_file',
        ),
    ]
