# Generated by Django 5.2.4 on 2026-05-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_lesson_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='dictionary_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
