# Generated by Django 5.2.4 on 2026-05-27 13:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usersetting_dictionary_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.lesson_file_upload_path),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.lesson_file_upload_path),
        ),
    ]
