# Generated by Django 5.2.4 on 2026-06-26 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_sentence_audio_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('record_img', models.CharField(blank=True, max_length=255, null=True)),
                ('record_name', models.CharField(max_length=30)),
                ('record_private', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(db_column='record_is_favorite', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('native_language', models.ForeignKey(db_column='nat_id', on_delete=django.db.models.deletion.CASCADE, related_name='record_native', to='api.language')),
                ('record_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_channel', to='api.channel')),
                ('record_lesson', models.ForeignKey(blank=True, db_column='lesson_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lesson')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
