# Generated by Django 5.2.4 on 2025-08-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='notifications',
            field=models.BooleanField(db_column='notifications', default=True),
        ),
    ]
