# Generated by Django 5.2.4 on 2026-08-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_translationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationmodel',
            name='source_language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='translationmodel',
            name='target_language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
