# Generated by Django 5.2.4 on 2025-08-03 19:47

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usersettings_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSettings',
            new_name='UserSetting',
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('doc_file', models.FileField(blank=True, null=True, upload_to=api.models.lesson_file_upload_path)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=api.models.audio_file_upload_path)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('native_language', models.CharField(max_length=50)),
                ('target_language', models.CharField(max_length=50)),
                ('lesson_private', models.BooleanField(default=True)),
                ('audioUploaded', models.BooleanField(default=True)),
                ('fileUploaded', models.BooleanField(default=True)),
                ('urlReference', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Lesson',
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
