# Generated by Django 5.2.4 on 2026-06-26 14:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='record_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.record_file_upload_path),
        ),
        migrations.AddField(
            model_name='recording',
            name='record_folder',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
