# Generated by Django 5.2.4 on 2026-05-27 18:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_lesson_audio_file_alter_lesson_doc_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.audio_file_upload_path),
        ),
    ]
