# Generated by Django 5.2.4 on 2026-08-11 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_translationmodel_source_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='translationModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_translation_model', to='api.translationmodel'),
        ),
    ]
