# Generated by Django 5.2.4 on 2026-08-28 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usersetting_translationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='last_seen',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
