# Generated by Django 5.2.4 on 2026-06-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_recording_record_file_recording_record_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='videoUploaded',
            field=models.BooleanField(default=False),
        ),
    ]
