# Generated by Django 5.2.4 on 2025-08-03 20:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_usersettings_usersetting_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='audioUploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='fileUploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='urlReference',
            field=models.BooleanField(default=False),
        ),
    ]
