# Generated by Django 5.2.4 on 2026-05-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_lesson_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='repeat_audio',
            field=models.BooleanField(db_column='repeat_audio', default=False),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='repeat_audio_all',
            field=models.BooleanField(db_column='repeat_audio_all', default=False),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='shuffle_audio',
            field=models.BooleanField(db_column='shuffle_audio', default=False),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='user_set_speed',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='user_set_volume',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
