# Generated by Django 5.2.4 on 2026-09-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userword_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='channel_tags', to='api.tag'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='lesson_tags', to='api.tag'),
        ),
        migrations.AddField(
            model_name='recording',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='record_tags', to='api.tag'),
        ),
    ]
