# Generated by Django 5.2.4 on 2026-06-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usersetting_repeat_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='end_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentence',
            name='start_ms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
