# Generated by Django 5.2.4 on 2025-08-03 20:23

from django.db import migrations

def populate_languages(apps, schema_editor):
    Language = apps.get_model('api', 'Language')
    language_list = ['English', 'Spanish', 'French', 'German', 'Lithuanian']
    for lang in language_list:
        Language.objects.get_or_create(lang_name=lang)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lesson_uuid_alter_lesson_audiouploaded_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_languages),
    ]
