# Generated by Django 5.2.4 on 2026-06-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lesson_videouploaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='videoUploaded',
            new_name='videoFormat',
        ),
    ]
