# Generated by Django 5.2.4 on 2026-07-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_videouploaded_lesson_videoformat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='audio_file',
            new_name='media_file',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='audio_folder',
            new_name='media_folder',
        ),
    ]
