# Generated by Django 5.2.4 on 2026-09-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tag_channel_tags_lesson_tags_recording_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_storage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='used_storage',
            field=models.IntegerField(default=0),
        ),
    ]
