# Generated by Django 5.2.4 on 2025-08-04 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_populate_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('audio_file', models.CharField(max_length=50)),
                ('sentence', models.CharField(max_length=250)),
                ('translated_sentence', models.CharField(max_length=250)),
                ('lesson_id', models.ForeignKey(db_column='lesson_id', on_delete=django.db.models.deletion.CASCADE, to='api.lesson')),
                ('lesson_language', models.ForeignKey(db_column='lesson_lang_id', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_sentences', to='api.language')),
                ('translate_language', models.ForeignKey(db_column='translate_lang_id', on_delete=django.db.models.deletion.CASCADE, related_name='translation_sentences', to='api.language')),
            ],
            options={
                'db_table': 'Sentence',
            },
        ),
    ]
