# Generated by Django 5.2.4 on 2025-08-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
