# Generated by Django 5.2.4 on 2026-07-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_audio_file_lesson_media_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='showVideoCaptions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='showVideoView',
            field=models.BooleanField(default=False),
        ),
    ]
