# Generated by Django 5.2.4 on 2026-06-12 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_word_frequency_alter_userword_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userword',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
