# Generated by Django 5.2.4 on 2026-06-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userword_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='tesseract_langcode',
            field=models.CharField(default='', max_length=25),
        ),
    ]
