# Generated by Django 5.2.4 on 2026-07-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_lesson_showvideocaptions_lesson_showvideoview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='showVideoCaptions',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='showVideoView',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='showVideoCaptions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='showVideoView',
            field=models.BooleanField(default=False),
        ),
    ]
