# Generated by Django 5.2.4 on 2026-09-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_storageobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_storage',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='used_storage',
            field=models.BigIntegerField(default=0),
        ),
    ]
