# Generated by Django 5.2.4 on 2026-06-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_language_tesseract_langcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='audio_file',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
