# Generated by Django 5.2.4 on 2025-08-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_lesson_title_alter_lesson_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
