# Generated by Django 5.2.4 on 2026-09-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_profile_total_storage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='record_private',
            new_name='is_public',
        ),
    ]
