# Generated by Django 5.2.4 on 2026-07-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_lesson_showvideocaptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='continuousPlay',
            field=models.BooleanField(default=False),
        ),
    ]
