# Generated by Django 5.2.4 on 2025-08-04 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_lesson_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_lesson',
            field=models.ForeignKey(db_column='lesson_id', default=7, on_delete=django.db.models.deletion.CASCADE, to='api.lesson'),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_lesson_index',
            field=models.SmallIntegerField(default=0),
        ),
    ]
