# Generated by Django 5.2.4 on 2026-09-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_record_private_recording_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='channel_private',
            new_name='is_public',
        ),
    ]
