# Generated by Django 5.2.4 on 2025-08-04 15:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_profile_current_lesson_profile_current_lesson_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_lesson_index',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='streak',
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_lesson',
            field=models.ForeignKey(db_column='lesson_id', default=7, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lesson'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserLessonsProgress',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('current_lesson_index', models.SmallIntegerField(default=0)),
                ('last_viewed', models.DateField(default=django.utils.timezone.now)),
                ('lesson_id', models.ForeignKey(db_column='lesson_id', default=7, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_lessons_progress',
                'unique_together': {('user', 'lesson_id')},
            },
        ),
    ]
