# Generated by Django 5.2.4 on 2026-09-10 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_channel_private_channel_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('dic_type', models.CharField(choices=[('website', 'Website'), ('pdf', 'PDF')], default='website', max_length=50)),
                ('is_public', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('native_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_native', to='api.language')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_target', to='api.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Dictionary',
            },
        ),
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_entries', to='api.dictionary')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_entries', to='api.word')),
            ],
            options={
                'db_table': 'DictionaryEntries',
                'constraints': [models.UniqueConstraint(fields=('word', 'dictionary'), name='unique_dictionary_entry')],
            },
        ),
    ]
