# Generated by Django 5.2.4 on 2025-08-04 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_profile_current_lesson_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_lesson',
            field=models.ForeignKey(db_column='lesson_progress', default=7, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userlessonsprogress'),
        ),
    ]
