# Generated by Django 5.2.4 on 2026-09-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_dictionary_dictionaryentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='dic_type',
            field=models.CharField(choices=[('website', 'Website'), ('pdf', 'PDF'), ('ai', 'AI')], default='website', max_length=50),
        ),
    ]
