# Generated by Django 5.2.4 on 2026-09-10 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_dictionary_dic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='native_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_native', to='api.language'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='target_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_target', to='api.language'),
        ),
    ]
