# Generated by Django 5.2.4 on 2025-08-05 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_profile_current_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_lesson',
            field=models.ForeignKey(db_column='lesson_progress', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userlessonsprogress'),
        ),
    ]
