# Generated by Django 5.2.4 on 2025-08-05 13:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_profile_current_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='userlessonsprogress',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.AlterUniqueTogether(
            name='userlessonsprogress',
            unique_together={('user', 'lesson')},
        ),
    ]
