# Generated by Django 5.2.4 on 2025-08-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_lesson_id_sentence_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audio_folder',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
