# Generated by Django 5.2.4 on 2026-09-10 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_dictionary_native_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='user_dictionary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_settings', to='api.dictionary'),
        ),
    ]
