# Generated by Django 5.2.4 on 2025-08-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_lesson_audio_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, default='images/default-01.jpg', null=True, upload_to='images/'),
        ),
    ]
