# Generated by Django 5.2.4 on 2025-08-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_lesson_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, default='images/default-01.jpg', null=True, upload_to=''),
        ),
    ]
