# Generated by Django 5.2.4 on 2026-09-11 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_usersetting_user_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryentry',
            name='native_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_entry_native', to='api.language'),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='target_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_entry_target', to='api.language'),
        ),
    ]
