# Generated by Django 5.2.4 on 2025-08-13 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_lesson_audio_file_alter_lesson_doc_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='native_language',
            field=models.ForeignKey(db_column='nat_id', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_native', to='api.language'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='target_language',
            field=models.ForeignKey(db_column='tar_id', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_target', to='api.language'),
        ),
    ]
