# Generated by Django 5.2.4 on 2026-09-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_dictionaryentry_native_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='dic_type',
            field=models.CharField(choices=[('website', 'Website'), ('file', 'FILE'), ('ai', 'AI')], default='website', max_length=50),
        ),
    ]
