# Generated by Django 5.2.4 on 2025-08-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_lesson_native_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='yt_dlp_lang',
            field=models.CharField(default='', max_length=25),
        ),
    ]
