# Generated by Django 5.2.4 on 2026-09-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_dictionary_dic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='dic_type',
            field=models.CharField(choices=[('website', 'Website'), ('file', 'File'), ('ai', 'AI')], default='website', max_length=50),
        ),
    ]
