# Generated by Django 5.2.4 on 2026-09-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_dictionary_dic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='offline_mode',
            field=models.BooleanField(db_column='offline_mode', default=False),
        ),
    ]
