# Generated by Django 5.2.4 on 2026-09-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_usersetting_offline_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='isScraperEnabled',
            field=models.BooleanField(default=False),
        ),
    ]
