# Generated by Django 5.2.4 on 2026-09-17 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_usersetting_isscraperenabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLanguageLessonIndex',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('lesson', models.ForeignKey(db_column='lesson_id', default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lesson')),
                ('lesson_language', models.ForeignKey(db_column='lesson_lang', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_lang_index', to='api.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_lesson_index', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
