# Generated by Django 5.2.4 on 2026-09-18 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_userlanguagelessonindex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlanguagelessonindex',
            unique_together={('user', 'lesson_language')},
        ),
        migrations.AddField(
            model_name='userlanguagelessonindex',
            name='lesson_progress',
            field=models.ForeignKey(db_column='lesson_index_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userlessonsprogress'),
        ),
        migrations.AlterModelTable(
            name='userlanguagelessonindex',
            table='user_language_lesson_index',
        ),
        migrations.RemoveField(
            model_name='userlanguagelessonindex',
            name='lesson',
        ),
    ]
