# Generated by Django 5.2.4 on 2026-09-18 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_userlanguagelessonindex_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguagelessonindex',
            name='lesson_progress',
            field=models.ForeignKey(blank=True, db_column='lesson_index_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userlessonsprogress'),
        ),
    ]
