# Generated by Django 5.2.4 on 2026-09-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_userlanguagelessonindex_lesson_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
