# Generated by Django 5.2.4 on 2026-10-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_aimodel_alter_usersetting_translationmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='purpose',
            field=models.CharField(choices=[('speech_to_text', 'Speech to Text'), ('text_to_text', 'Text to Text'), ('text_to_speech', 'Text to Speech'), ('image_to_text', 'Image to Text'), ('other', 'Other')], default='other', max_length=50),
            preserve_default=False,
        ),
    ]
