# Generated by Django 5.2.4 on 2026-10-02 15:52

import django.db.models.deletion
from django.db import migrations, models


def copy_translation_model(apps, schema_editor):
    UserSetting = apps.get_model("api", "UserSetting")

    UserSetting.objects.exclude(
        translationModel=None
    ).update(
        textToTextModel_id=models.F("translationModel_id")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_aimodel_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersetting",
            name="imageToTextModel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settings_image_to_text_model",
                to="api.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="speechToTextModel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settings_speech_to_text_model",
                to="api.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="textToSpeechModel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settings_text_to_speech_model",
                to="api.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="textToTextModel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settings_text_to_text_model",
                to="api.aimodel",
            ),
        ),
        migrations.RunPython(
            copy_translation_model,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="usersetting",
            name="translationModel",
        ),
    ]