# Generated by Django 5.2.4 on 2026-10-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_usersetting_translationmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audioGenerated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='videoGenerated',
            field=models.BooleanField(default=False),
        ),
    ]
