# Generated by Django 5.2.4 on 2026-10-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_lesson_audiogenerated_lesson_videogenerated'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='sentencesReordered',
            field=models.BooleanField(default=False),
        ),
    ]
