version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: langue_backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
    expose:
      - "8000"

  frontend:
    build:
      context: ./mobile-frontend/mobile-app
      dockerfile: Dockerfile
    container_name: langue_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
